### ISSUE TITLE
Add optional arg to 'getItem' to specify default value

### ISSUE THREAD

**Issue by zuck** [MatteoGabriele/storage-helper#3]
It would be very useful to add a third (optional) argument to the `getItem` signature in order to be able to specify a default returned value in case the key is not already present in the storage, e.g.:

```js
var language = storageHelper.getItem('language', false, 'en')
```

**Comment by MatteoGabriele** [comment]
@zuck  I've added the feature in the v1.4.0 :)

**update** v1.4.1

**Comment by zuck** [comment]
Great, thank you!

Maybe it's better to update README too with an example of its use.
